### ISSUE TITLE
## Install Python Requirements

### ISSUE THREAD

**Issue by BahaaMansour** [IBM/powerai-counting-cars#22]
I tried to run "Install Python Requirements" to see if i have missing documents, but i received multiple errors such as
1.###  **"**_Could not find a version that satisfies the requirement opencv-python==3.4.0.12 (from versions: 3.4.2.16, 3.4.2.17, 3.4.3.18)
No matching distribution found for opencv-python==3.4.0.12"_****
2. "Could not find a version that satisfies the requirement opencv-contrib-python==3.4.0.12 (from versions: 3.4.2.16, 3.4.2.17, 3.4.3.18)

No matching distribution found for opencv-contrib-python==3.4.0.12"
3. "Command "c:\users\bahaa\anaconda3\python.exe -m pip install --ignore-installed --no-user --prefix C:\Users\Bahaa\AppData\Local\Temp\pip-build-env-4840oel0 --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools Cython "numpy==1.9.3; python_version=='3.5'" "numpy==1.12.1; python_version=='3.6'" "numpy==1.13.1; python_version>='3.7'"" failed with error code 1 in None"

Even though i already have opencv-python 3.4.4.19 & opencv-contrib-python latest version. Do i ignore these errors?

Kindly Find attached files.
![screen shot of the issue](https://user-images.githubusercontent.com/44228249/49133050-0a18aa80-f2f8-11e8-9a19-aa3f8719a779.png)
![proof of opencv installation](https://user-images.githubusercontent.com/44228249/49133054-0e44c800-f2f8-11e8-880e-defabf37145b.png)

Thank you

**Comment by markstur** [comment]
We're pinning the versions to the latest versions we tested. You might want to try more current versions and comment out (or update) the pip commands.  I just updated them in PR #23 .

Also the error can happen due to old versions of pip or wheel requirements that are not on your platform. Should not be much of a problem if you were able to install more current versions, though. So we'll just update.
